### ISSUE TITLE
Task list for rotary

### ISSUE THREAD

**Issue by jmtsuji** [rotary-genomics/rotary#15]
Can be converted to issues if complex:

Usability / reproducibility:
- [ ] #156
- [x] Make a proper front-end CLI (see rotary-genomics/rotary#23 )
- [x] Add short read QC or at least code in the repo that shows how to do short read QC
- [ ] ~End-to-end test with proper hash comparisons (need to find some deterministic endpoints)~ Too hard with current CI  systems and pipeline size - low priority.
- [x] Install scripts properly (e.g., make the whole thing a pip and/or conda install) so that downloading the release to the downloads folder (in the snakefile) is no longer needed 
- [x] Split snakefile into multiple files
- [ ] #157

Low priority:
- [x] Add support for well-parallelized medaka
- [ ] #158
- [ ] #159
- [ ] #160

**Comment by LeeBergstrand** [comment]
@jmtsuji Moved to individual issues.

**Comment by jmtsuji** [comment]
Thanks!
